//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edocsys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Справочники")]
        public string CatalogToolStripMenuText {
            get {
                return ((string)(this["CatalogToolStripMenuText"]));
            }
            set {
                this["CatalogToolStripMenuText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Система регистрации заявок")]
        public string MainFormText {
            get {
                return ((string)(this["MainFormText"]));
            }
            set {
                this["MainFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Файл")]
        public string FileToolStripMenuItemText {
            get {
                return ((string)(this["FileToolStripMenuItemText"]));
            }
            set {
                this["FileToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Начать сеанс")]
        public string LoginToolStripMenuItemText {
            get {
                return ((string)(this["LoginToolStripMenuItemText"]));
            }
            set {
                this["LoginToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выход")]
        public string ExitToolStripMenuItemText {
            get {
                return ((string)(this["ExitToolStripMenuItemText"]));
            }
            set {
                this["ExitToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Администрирование")]
        public string AdmToolStripMenuItemText {
            get {
                return ((string)(this["AdmToolStripMenuItemText"]));
            }
            set {
                this["AdmToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Панель Администрирования")]
        public string AdmpanelToolStripMenuItemText {
            get {
                return ((string)(this["AdmpanelToolStripMenuItemText"]));
            }
            set {
                this["AdmpanelToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначение эксперта")]
        public string AssignexpertToolStripMenuItemText {
            get {
                return ((string)(this["AssignexpertToolStripMenuItemText"]));
            }
            set {
                this["AssignexpertToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Эксперты")]
        public string AddingExpertToolStripMenuItemText {
            get {
                return ((string)(this["AddingExpertToolStripMenuItemText"]));
            }
            set {
                this["AddingExpertToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Этапы работы")]
        public string DocToolStripMenuItemText {
            get {
                return ((string)(this["DocToolStripMenuItemText"]));
            }
            set {
                this["DocToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Контрагенты")]
        public string ContractorToolStripMenuItemText {
            get {
                return ((string)(this["ContractorToolStripMenuItemText"]));
            }
            set {
                this["ContractorToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявки")]
        public string ProposalToolStripMenuItemText {
            get {
                return ((string)(this["ProposalToolStripMenuItemText"]));
            }
            set {
                this["ProposalToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ведение договоров")]
        public string ContractToolStripMenuItemText {
            get {
                return ((string)(this["ContractToolStripMenuItemText"]));
            }
            set {
                this["ContractToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Помощь")]
        public string HelpToolStripMenuItemText {
            get {
                return ((string)(this["HelpToolStripMenuItemText"]));
            }
            set {
                this["HelpToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Класс продукции")]
        public string product_nameLabelText {
            get {
                return ((string)(this["product_nameLabelText"]));
            }
            set {
                this["product_nameLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Код ОКП")]
        public string product_OKPLabelText {
            get {
                return ((string)(this["product_OKPLabelText"]));
            }
            set {
                this["product_OKPLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Код ТНВД")]
        public string product_TNVEDLabelText {
            get {
                return ((string)(this["product_TNVEDLabelText"]));
            }
            set {
                this["product_TNVEDLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Окна")]
        public string WindowToolStripMenuItemText {
            get {
                return ((string)(this["WindowToolStripMenuItemText"]));
            }
            set {
                this["WindowToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявки")]
        public string ProposalFormText {
            get {
                return ((string)(this["ProposalFormText"]));
            }
            set {
                this["ProposalFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.4")]
        public string ConnHost {
            get {
                return ((string)(this["ConnHost"]));
            }
            set {
                this["ConnHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string ConnPort {
            get {
                return ((string)(this["ConnPort"]));
            }
            set {
                this["ConnPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("edocbase")]
        public string ConnDatabase {
            get {
                return ((string)(this["ConnDatabase"]));
            }
            set {
                this["ConnDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Наименование продукции")]
        public string ProposalEmissionLabelText {
            get {
                return ((string)(this["ProposalEmissionLabelText"]));
            }
            set {
                this["ProposalEmissionLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Учредительные документы")]
        public string ProposalClientDocsLabelText {
            get {
                return ((string)(this["ProposalClientDocsLabelText"]));
            }
            set {
                this["ProposalClientDocsLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Схема сертификации")]
        public string ProposalSchemeTypeLabelText {
            get {
                return ((string)(this["ProposalSchemeTypeLabelText"]));
            }
            set {
                this["ProposalSchemeTypeLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дополнительные сведения")]
        public string ProposalAddDataLabelText {
            get {
                return ((string)(this["ProposalAddDataLabelText"]));
            }
            set {
                this["ProposalAddDataLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Тип договора")]
        public string ProposalContractTypeLabelText {
            get {
                return ((string)(this["ProposalContractTypeLabelText"]));
            }
            set {
                this["ProposalContractTypeLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Область аккредитации")]
        public string ProductionToolStripMenuItemText {
            get {
                return ((string)(this["ProductionToolStripMenuItemText"]));
            }
            set {
                this["ProductionToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Область аккредитации")]
        public string ProductionFormText {
            get {
                return ((string)(this["ProductionFormText"]));
            }
            set {
                this["ProductionFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Эксперты")]
        public string ExpertsFormText {
            get {
                return ((string)(this["ExpertsFormText"]));
            }
            set {
                this["ExpertsFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Контрагенты")]
        public string ClientsFormText {
            get {
                return ((string)(this["ClientsFormText"]));
            }
            set {
                this["ClientsFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Полное название")]
        public string AgentsFullNameText {
            get {
                return ((string)(this["AgentsFullNameText"]));
            }
            set {
                this["AgentsFullNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сокращенное название")]
        public string AgentsShortNameText {
            get {
                return ((string)(this["AgentsShortNameText"]));
            }
            set {
                this["AgentsShortNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Адрес")]
        public string AgentsAddressText {
            get {
                return ((string)(this["AgentsAddressText"]));
            }
            set {
                this["AgentsAddressText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Телефон")]
        public string AgentsPhoneText {
            get {
                return ((string)(this["AgentsPhoneText"]));
            }
            set {
                this["AgentsPhoneText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Факс")]
        public string AgentsFaxText {
            get {
                return ((string)(this["AgentsFaxText"]));
            }
            set {
                this["AgentsFaxText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E-mail")]
        public string AgentsEMailText {
            get {
                return ((string)(this["AgentsEMailText"]));
            }
            set {
                this["AgentsEMailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Контактная информация")]
        public string AgentsContactInformationText {
            get {
                return ((string)(this["AgentsContactInformationText"]));
            }
            set {
                this["AgentsContactInformationText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Реквизиты")]
        public string AgentsBankInformationText {
            get {
                return ((string)(this["AgentsBankInformationText"]));
            }
            set {
                this["AgentsBankInformationText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ИНН")]
        public string AgentsINNText {
            get {
                return ((string)(this["AgentsINNText"]));
            }
            set {
                this["AgentsINNText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ОГРН")]
        public string AgentsOGRNText {
            get {
                return ((string)(this["AgentsOGRNText"]));
            }
            set {
                this["AgentsOGRNText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("КПП")]
        public string AgentsKPPText {
            get {
                return ((string)(this["AgentsKPPText"]));
            }
            set {
                this["AgentsKPPText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ОКПО")]
        public string AgentsOKPOText {
            get {
                return ((string)(this["AgentsOKPOText"]));
            }
            set {
                this["AgentsOKPOText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Кор/счет")]
        public string AgentsKSText {
            get {
                return ((string)(this["AgentsKSText"]));
            }
            set {
                this["AgentsKSText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Р/счет")]
        public string AgentsRSText {
            get {
                return ((string)(this["AgentsRSText"]));
            }
            set {
                this["AgentsRSText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("БИК")]
        public string AgentsBIKText {
            get {
                return ((string)(this["AgentsBIKText"]));
            }
            set {
                this["AgentsBIKText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Наименование банка")]
        public string AgentsBankText {
            get {
                return ((string)(this["AgentsBankText"]));
            }
            set {
                this["AgentsBankText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Руководитель организации")]
        public string AgentsContactPersonText {
            get {
                return ((string)(this["AgentsContactPersonText"]));
            }
            set {
                this["AgentsContactPersonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Действующий на основании")]
        public string AgentsDocText {
            get {
                return ((string)(this["AgentsDocText"]));
            }
            set {
                this["AgentsDocText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Должность")]
        public string AgentsPersonStatusText {
            get {
                return ((string)(this["AgentsPersonStatusText"]));
            }
            set {
                this["AgentsPersonStatusText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Имя")]
        public string AgentsPersonFirstNameText {
            get {
                return ((string)(this["AgentsPersonFirstNameText"]));
            }
            set {
                this["AgentsPersonFirstNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Фамилия")]
        public string AgentsPersonLastNameText {
            get {
                return ((string)(this["AgentsPersonLastNameText"]));
            }
            set {
                this["AgentsPersonLastNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отчество")]
        public string AgentsPersonMiddleNameText {
            get {
                return ((string)(this["AgentsPersonMiddleNameText"]));
            }
            set {
                this["AgentsPersonMiddleNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Настройки")]
        public string ConfigFormText {
            get {
                return ((string)(this["ConfigFormText"]));
            }
            set {
                this["ConfigFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранить")]
        public string ConfigSaveText {
            get {
                return ((string)(this["ConfigSaveText"]));
            }
            set {
                this["ConfigSaveText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отмена")]
        public string ConfigCancelText {
            get {
                return ((string)(this["ConfigCancelText"]));
            }
            set {
                this["ConfigCancelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Хост")]
        public string ConfigHostText {
            get {
                return ((string)(this["ConfigHostText"]));
            }
            set {
                this["ConfigHostText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Порт")]
        public string ConfigPortText {
            get {
                return ((string)(this["ConfigPortText"]));
            }
            set {
                this["ConfigPortText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Имя базы данных")]
        public string ConfigDatabaseText {
            get {
                return ((string)(this["ConfigDatabaseText"]));
            }
            set {
                this["ConfigDatabaseText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сборосить")]
        public string ConfigResetToDefaults {
            get {
                return ((string)(this["ConfigResetToDefaults"]));
            }
            set {
                this["ConfigResetToDefaults"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Проверить подключение")]
        public string ConfigTestConnectionText {
            get {
                return ((string)(this["ConfigTestConnectionText"]));
            }
            set {
                this["ConfigTestConnectionText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("log.txt")]
        public string LogFilename {
            get {
                return ((string)(this["LogFilename"]));
            }
            set {
                this["LogFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначение эксперта")]
        public string AssighExpertFormText {
            get {
                return ((string)(this["AssighExpertFormText"]));
            }
            set {
                this["AssighExpertFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначить эксперта")]
        public string AssignExpertTabText {
            get {
                return ((string)(this["AssignExpertTabText"]));
            }
            set {
                this["AssignExpertTabText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначенные эксперты/Статистика по заключению договоров")]
        public string AssignedExpertTabText {
            get {
                return ((string)(this["AssignedExpertTabText"]));
            }
            set {
                this["AssignedExpertTabText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Эксперты")]
        public string AssignExpertExpertsText {
            get {
                return ((string)(this["AssignExpertExpertsText"]));
            }
            set {
                this["AssignExpertExpertsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Название контрагента")]
        public string ProposalAgentNameText {
            get {
                return ((string)(this["ProposalAgentNameText"]));
            }
            set {
                this["ProposalAgentNameText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Эксперт")]
        public string AssignExprtsExpertText {
            get {
                return ((string)(this["AssignExprtsExpertText"]));
            }
            set {
                this["AssignExprtsExpertText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявка")]
        public string AssignExpertProposalText {
            get {
                return ((string)(this["AssignExpertProposalText"]));
            }
            set {
                this["AssignExpertProposalText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначить")]
        public string AssignExpertsAssignButtonText {
            get {
                return ((string)(this["AssignExpertsAssignButtonText"]));
            }
            set {
                this["AssignExpertsAssignButtonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вход")]
        public string LoginFormText {
            get {
                return ((string)(this["LoginFormText"]));
            }
            set {
                this["LoginFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Отмена")]
        public string LoginFormCancelText {
            get {
                return ((string)(this["LoginFormCancelText"]));
            }
            set {
                this["LoginFormCancelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Войти")]
        public string LoginFormLoginText {
            get {
                return ((string)(this["LoginFormLoginText"]));
            }
            set {
                this["LoginFormLoginText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Форма собственности")]
        public string AgentsTypeName {
            get {
                return ((string)(this["AgentsTypeName"]));
            }
            set {
                this["AgentsTypeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дополнительные контакты")]
        public string AgentsContactsText {
            get {
                return ((string)(this["AgentsContactsText"]));
            }
            set {
                this["AgentsContactsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблоны документов")]
        public string DocTemplatesTitle {
            get {
                return ((string)(this["DocTemplatesTitle"]));
            }
            set {
                this["DocTemplatesTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Шаблон не выбран")]
        public string DocTemplateOperationsText {
            get {
                return ((string)(this["DocTemplateOperationsText"]));
            }
            set {
                this["DocTemplateOperationsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Договора")]
        public string ContractsFormTitle {
            get {
                return ((string)(this["ContractsFormTitle"]));
            }
            set {
                this["ContractsFormTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Неподписанные договора")]
        public string TabExpertAssigned {
            get {
                return ((string)(this["TabExpertAssigned"]));
            }
            set {
                this["TabExpertAssigned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Договора в работе")]
        public string TabTaskProcessed {
            get {
                return ((string)(this["TabTaskProcessed"]));
            }
            set {
                this["TabTaskProcessed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Подтверждение выполнения договора")]
        public string TabTaskReady {
            get {
                return ((string)(this["TabTaskReady"]));
            }
            set {
                this["TabTaskReady"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выдача акта и подтверждение клиентом")]
        public string TabTaskFinished {
            get {
                return ((string)(this["TabTaskFinished"]));
            }
            set {
                this["TabTaskFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Невыполненные задания")]
        public string TabBadJob {
            get {
                return ((string)(this["TabBadJob"]));
            }
            set {
                this["TabBadJob"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Загрузить шаблон документа")]
        public string LoadTemplateButton {
            get {
                return ((string)(this["LoadTemplateButton"]));
            }
            set {
                this["LoadTemplateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Изменить шаблон документа")]
        public string EditTemplateButton {
            get {
                return ((string)(this["EditTemplateButton"]));
            }
            set {
                this["EditTemplateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранить шаблон на диск")]
        public string SaveTemplateButton {
            get {
                return ((string)(this["SaveTemplateButton"]));
            }
            set {
                this["SaveTemplateButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Наличие загруженного шаблона")]
        public string TemplatePresenceText {
            get {
                return ((string)(this["TemplatePresenceText"]));
            }
            set {
                this["TemplatePresenceText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сгенерировать заявку")]
        public string GenerateProposalTitle {
            get {
                return ((string)(this["GenerateProposalTitle"]));
            }
            set {
                this["GenerateProposalTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Редактировать файл заявки")]
        public string EditProposalButton {
            get {
                return ((string)(this["EditProposalButton"]));
            }
            set {
                this["EditProposalButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Операции с документом заявки")]
        public string ProposalOperationsGroupBox {
            get {
                return ((string)(this["ProposalOperationsGroupBox"]));
            }
            set {
                this["ProposalOperationsGroupBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранть файл заявки на диск")]
        public string SaveProposalButton {
            get {
                return ((string)(this["SaveProposalButton"]));
            }
            set {
                this["SaveProposalButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Загрузить файл заявки с диска")]
        public string LoadProposalButton {
            get {
                return ((string)(this["LoadProposalButton"]));
            }
            set {
                this["LoadProposalButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вид проводимых работ")]
        public string ContractTypeText {
            get {
                return ((string)(this["ContractTypeText"]));
            }
            set {
                this["ContractTypeText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Операции с договором")]
        public string ContractOperationGroupBox {
            get {
                return ((string)(this["ContractOperationGroupBox"]));
            }
            set {
                this["ContractOperationGroupBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сгенерировать договор")]
        public string GenerateContractTitle {
            get {
                return ((string)(this["GenerateContractTitle"]));
            }
            set {
                this["GenerateContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Номер договора")]
        public string ContractNumberTitle {
            get {
                return ((string)(this["ContractNumberTitle"]));
            }
            set {
                this["ContractNumberTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Редактировать файл договора")]
        public string EditContractTitle {
            get {
                return ((string)(this["EditContractTitle"]));
            }
            set {
                this["EditContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранть файл договора на диск")]
        public string SaveContractTitle {
            get {
                return ((string)(this["SaveContractTitle"]));
            }
            set {
                this["SaveContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Загрузить файл договора с диска")]
        public string LoadContractTitle {
            get {
                return ((string)(this["LoadContractTitle"]));
            }
            set {
                this["LoadContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Область аккредитации")]
        public string ProductAreasTitle {
            get {
                return ((string)(this["ProductAreasTitle"]));
            }
            set {
                this["ProductAreasTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выбор ГОСТов")]
        public string GOSTSelectionTitle {
            get {
                return ((string)(this["GOSTSelectionTitle"]));
            }
            set {
                this["GOSTSelectionTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Номер договора")]
        public string ContractsNumberTitle {
            get {
                return ((string)(this["ContractsNumberTitle"]));
            }
            set {
                this["ContractsNumberTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дата заключения договора")]
        public string ContractDateCTitle {
            get {
                return ((string)(this["ContractDateCTitle"]));
            }
            set {
                this["ContractDateCTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дата начала работ")]
        public string ContractsDateStartTitle {
            get {
                return ((string)(this["ContractsDateStartTitle"]));
            }
            set {
                this["ContractsDateStartTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дата поступления образца")]
        public string ContractsDateSampleIncomeTitle {
            get {
                return ((string)(this["ContractsDateSampleIncomeTitle"]));
            }
            set {
                this["ContractsDateSampleIncomeTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дата поступления протокола")]
        public string ContractsDateProtocolIncomeTitle {
            get {
                return ((string)(this["ContractsDateProtocolIncomeTitle"]));
            }
            set {
                this["ContractsDateProtocolIncomeTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Планирование выполнения работ")]
        public string PreparationsForTaskTitle {
            get {
                return ((string)(this["PreparationsForTaskTitle"]));
            }
            set {
                this["PreparationsForTaskTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дата окончания работ")]
        public string ContractDateEndTitle {
            get {
                return ((string)(this["ContractDateEndTitle"]));
            }
            set {
                this["ContractDateEndTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заключение договора инспекционного контроля")]
        public string ReattestationSignTitle {
            get {
                return ((string)(this["ReattestationSignTitle"]));
            }
            set {
                this["ReattestationSignTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Договора на инспекционном контроле")]
        public string InspectionControlTitle {
            get {
                return ((string)(this["InspectionControlTitle"]));
            }
            set {
                this["InspectionControlTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Завершенные договора")]
        public string FinishedTasksTitle {
            get {
                return ((string)(this["FinishedTasksTitle"]));
            }
            set {
                this["FinishedTasksTitle"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=192.168.0.4;Port=3306;User Id=root;password=po12jein45bf;Persist Security " +
            "Info=True;database=edocbase")]
        public string EdocbaseConnectionString {
            get {
                return ((string)(this["EdocbaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Планирование работ")]
        public string WorksForContractTitle {
            get {
                return ((string)(this["WorksForContractTitle"]));
            }
            set {
                this["WorksForContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оплата договоров")]
        public string ContractPaymentsTitle {
            get {
                return ((string)(this["ContractPaymentsTitle"]));
            }
            set {
                this["ContractPaymentsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Инспекционный контроль")]
        public string InspectionControlMenuTitle {
            get {
                return ((string)(this["InspectionControlMenuTitle"]));
            }
            set {
                this["InspectionControlMenuTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Статистика договоров")]
        public string ContractStatsTitle {
            get {
                return ((string)(this["ContractStatsTitle"]));
            }
            set {
                this["ContractStatsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Операции с актами")]
        public string ContractActTitle {
            get {
                return ((string)(this["ContractActTitle"]));
            }
            set {
                this["ContractActTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Оплаченые договора")]
        public string PayedContractsTitle {
            get {
                return ((string)(this["PayedContractsTitle"]));
            }
            set {
                this["PayedContractsTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сгенерировать акт выполнения работ")]
        public string GenerateActTitle {
            get {
                return ((string)(this["GenerateActTitle"]));
            }
            set {
                this["GenerateActTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Редактировать файл акта")]
        public string ActEditTitle {
            get {
                return ((string)(this["ActEditTitle"]));
            }
            set {
                this["ActEditTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Сохранить файл акта на диск")]
        public string ActSaveTitle {
            get {
                return ((string)(this["ActSaveTitle"]));
            }
            set {
                this["ActSaveTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Загрузить файл акта с диска")]
        public string ActLoadTitle {
            get {
                return ((string)(this["ActLoadTitle"]));
            }
            set {
                this["ActLoadTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Операции с договором инспекционного контроля")]
        public string ReattContractTitle {
            get {
                return ((string)(this["ReattContractTitle"]));
            }
            set {
                this["ReattContractTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Формы собственности")]
        public string AgentTypesTitle {
            get {
                return ((string)(this["AgentTypesTitle"]));
            }
            set {
                this["AgentTypesTitle"] = value;
            }
        }
    }
}
