//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Edocsys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Справочники")]
        public string CatalogToolStripMenuText {
            get {
                return ((string)(this["CatalogToolStripMenuText"]));
            }
            set {
                this["CatalogToolStripMenuText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Система регистрации заявок")]
        public string MainFormText {
            get {
                return ((string)(this["MainFormText"]));
            }
            set {
                this["MainFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Файл")]
        public string FileToolStripMenuItemText {
            get {
                return ((string)(this["FileToolStripMenuItemText"]));
            }
            set {
                this["FileToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Вход")]
        public string LoginToolStripMenuItemText {
            get {
                return ((string)(this["LoginToolStripMenuItemText"]));
            }
            set {
                this["LoginToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Выход")]
        public string ExitToolStripMenuItemText {
            get {
                return ((string)(this["ExitToolStripMenuItemText"]));
            }
            set {
                this["ExitToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Администрирование")]
        public string AdmToolStripMenuItemText {
            get {
                return ((string)(this["AdmToolStripMenuItemText"]));
            }
            set {
                this["AdmToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Панель Администрирования")]
        public string AdmpanelToolStripMenuItemText {
            get {
                return ((string)(this["AdmpanelToolStripMenuItemText"]));
            }
            set {
                this["AdmpanelToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Назначение эксперта")]
        public string AssignexpertToolStripMenuItemText {
            get {
                return ((string)(this["AssignexpertToolStripMenuItemText"]));
            }
            set {
                this["AssignexpertToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Добавление эксперта")]
        public string AddingExpertToolStripMenuItemText {
            get {
                return ((string)(this["AddingExpertToolStripMenuItemText"]));
            }
            set {
                this["AddingExpertToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Документы")]
        public string DocToolStripMenuItemText {
            get {
                return ((string)(this["DocToolStripMenuItemText"]));
            }
            set {
                this["DocToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Контрагенты")]
        public string ContractorToolStripMenuItemText {
            get {
                return ((string)(this["ContractorToolStripMenuItemText"]));
            }
            set {
                this["ContractorToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Продукция")]
        public string ProductionToolStripMenuItemText {
            get {
                return ((string)(this["ProductionToolStripMenuItemText"]));
            }
            set {
                this["ProductionToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявки")]
        public string ProposalToolStripMenuItemText {
            get {
                return ((string)(this["ProposalToolStripMenuItemText"]));
            }
            set {
                this["ProposalToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Договора")]
        public string ContractToolStripMenuItemText {
            get {
                return ((string)(this["ContractToolStripMenuItemText"]));
            }
            set {
                this["ContractToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("&Помощь")]
        public string HelpToolStripMenuItemText {
            get {
                return ((string)(this["HelpToolStripMenuItemText"]));
            }
            set {
                this["HelpToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=10.0.2.2;User Id=defuser;password=ttrr;Persist Security Info=True;database" +
            "=Edocbase")]
        public string EdocbaseConnectionString {
            get {
                return ((string)(this["EdocbaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Наименование продукции")]
        public string product_nameLabelText {
            get {
                return ((string)(this["product_nameLabelText"]));
            }
            set {
                this["product_nameLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Код ОКП")]
        public string product_OKPLabelText {
            get {
                return ((string)(this["product_OKPLabelText"]));
            }
            set {
                this["product_OKPLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Код ТНВД")]
        public string product_TNVEDLabelText {
            get {
                return ((string)(this["product_TNVEDLabelText"]));
            }
            set {
                this["product_TNVEDLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Продукция")]
        public string ProductionFormText {
            get {
                return ((string)(this["ProductionFormText"]));
            }
            set {
                this["ProductionFormText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Окна")]
        public string WindowToolStripMenuItemText {
            get {
                return ((string)(this["WindowToolStripMenuItemText"]));
            }
            set {
                this["WindowToolStripMenuItemText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>00 - Заявка добавлена</string>
  <string>01 - К заявке прикреплен эксперт</string>
  <string>02 - Начата работа</string>
  <string>03 - Оформлен акт выполненных работ</string>
  <string>04 - Акт утверден руководителем</string>
  <string>20 - Договор исполнен</string>
  <string>21 - Заказчик  Эл. Джон</string>
  <string>22 - Эксперт  Эл. Джон</string>
  <string>23 - Директор  Эл. Джон</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ContractStatuses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ContractStatuses"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10 - Договор оформлен</string>
  <string>11 - Договор подписан</string>
  <string>12 - Перечислен аванс</string>
  <string>13 - Перечислена полная сумма</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PaymentStatuses {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PaymentStatuses"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Заявки")]
        public string ProposalFormText {
            get {
                return ((string)(this["ProposalFormText"]));
            }
            set {
                this["ProposalFormText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("host=localhost;Port=3309;User Id=defuser;password=ttrr;Persist Security Info=True" +
            ";database=Edocbase")]
        public string EdocbaseConnectionStringHomeVolik {
            get {
                return ((string)(this["EdocbaseConnectionStringHomeVolik"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=10.0.2.2;User Id=defuser;password=ttrr;Persist Security Info=True;database" +
            "=Edocbase")]
        public string EdocbaseConnectionStringServer {
            get {
                return ((string)(this["EdocbaseConnectionStringServer"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.137.85")]
        public string ConnHost {
            get {
                return ((string)(this["ConnHost"]));
            }
            set {
                this["ConnHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public string ConnPort {
            get {
                return ((string)(this["ConnPort"]));
            }
            set {
                this["ConnPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Edocbase")]
        public string ConnDatabase {
            get {
                return ((string)(this["ConnDatabase"]));
            }
            set {
                this["ConnDatabase"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("host=localhost;User Id=defuser;password=ttrr;Persist Security Info=True;database=" +
            "Edocbase")]
        public string EdocbaseConnectionStringHomeMicresh {
            get {
                return ((string)(this["EdocbaseConnectionStringHomeMicresh"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Тип выпуска продукции")]
        public string ProposalEmissionLabelText {
            get {
                return ((string)(this["ProposalEmissionLabelText"]));
            }
            set {
                this["ProposalEmissionLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Учредительные документы")]
        public string ProposalClientDocsLabelText {
            get {
                return ((string)(this["ProposalClientDocsLabelText"]));
            }
            set {
                this["ProposalClientDocsLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Схема сертификации")]
        public string ProposalSchemeTypeLabelText {
            get {
                return ((string)(this["ProposalSchemeTypeLabelText"]));
            }
            set {
                this["ProposalSchemeTypeLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Дополнительные сведения")]
        public string ProposalAddDataLabelText {
            get {
                return ((string)(this["ProposalAddDataLabelText"]));
            }
            set {
                this["ProposalAddDataLabelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Тип договора")]
        public string ProposalContractTypeLabelText {
            get {
                return ((string)(this["ProposalContractTypeLabelText"]));
            }
            set {
                this["ProposalContractTypeLabelText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("host=localhost;Port=3309;User Id=root;password=po12jein45bf;Persist Security Info" +
            "=True;database=Edocbase")]
        public string EdocbaseConnectionStringHomeVolikRoot {
            get {
                return ((string)(this["EdocbaseConnectionStringHomeVolikRoot"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("server=10.0.2.2;User Id=root;database=Edocbase;Persist Security Info=True")]
        public string EdocbaseConnectionString1 {
            get {
                return ((string)(this["EdocbaseConnectionString1"]));
            }
        }
    }
}
